# Lighter version inspired by https://github.com/r-lib/actions/blob/v2-branch/examples/check-no-suggests.yaml
name: R-CMD-check (no Suggests)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          cache: false
          use-public-rspm: true

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '--no-manual --as-cran'
          build-vignettes: false
